HairSalon/Models/Client.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel;

namespace EauSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }
    public int StylistId { get; set; }
    [DisplayName("Client Name:")]
    public string Name { get; set; }
    [DisplayName("Preferred Appointment Days:")]
    public string PreferredDays { get; set; }
    [DisplayName("Would the client like to be contacted about last minute openings:")]
    public Notice ShortNotice { get; set; }
    public virtual Stylist Stylist { get; set; }
  }

  public enum Notice
  {
    No,
    Yes
  }
}

HairSalon/Models/EauSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace EauSalon.Models
{
  public class EauSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }
    public EauSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;
using System.ComponentModel;
using System;

namespace EauSalon.Models
{
  public class Stylist
  {
    public Stylist()
    {
      this.Clients = new HashSet<Client>();
    }

    public int StylistId { get; set; }
    [DisplayName("Stylist's Name:")]
    public string Name { get; set; }
    // [DisplayName("Hire Date:")]
    // public DateTime HireDate { get; set; }
    // [DisplayName("Scheduled Work Day:")]
    // public WorkDay ScheduledWorkDays { get; set; }

    public virtual ICollection<Client> Clients { get; set; }
  }

  // public enum WorkDay
  // {
  //   Monday,
  //   Tuesday,
  //   Wednesday,
  //   Thursday,
  //   Friday,
  //   Saturday
  // }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using EauSalon.Models; 
using System.Linq;

namespace EauSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly EauSalonContext _db;
    
    public ClientsController(EauSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      ViewBag.ShortNotice = new SelectList(_db.Clients, "ShortNotice", "Short Notice Appointment");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      // List<Client> model = _db.Clients.Include(clients => clients.Stylist).ToList();
      Client thisClient = _db.Clients.FirstOrDefault(clients => clients.ClientId == id);
      return View(thisClient);
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace EauSalon.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      return View();
    }
  }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using EauSalon.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace EauSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly EauSalonContext _db; //create datatype EauSalonContex, name it _db
    public StylistsController(EauSalonContext db) //set value of _db created above to the database
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      // ViewBag.WorkDay = new SelectList(_db.Stylists, "ScheduledWorkDays", "Scheduled Work Day");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
      return View (thisStylist);
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauSalon.Models.Client
@using EauSalon.Models

<h3>Add a new Eau Salon Client record</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
  <br>
  @Html.LabelFor(model => model.PreferredDays)
  @Html.TextBoxFor(model => model.PreferredDays, new { @class = "form-control"})
  <br>
  @Html.LabelFor(model => model.ShortNotice)
  @Html.DropDownList("ShortNotice",
      new SelectList(Enum.GetValues(typeof(Notice))),
      new { @class = "form-control" })
  <br>
  @Html.LabelFor(model => model.Stylist)
  @Html.DropDownList("StylistId", null, new { @class = "form-control"})

  <input type="submit" value="Add a Client" class="btn btn-default" />
}

<div class="linked">
  <p>@Html.ActionLink("See list of EauSalon Clients", "Index", "Clients")</p>
  <p>@Html.ActionLink("Add a new record for an EauSalon Stylist", "Create", "Stylists")</p>
  <p>@Html.ActionLink("See list of EauSalon Stylists", "Index", "Stylists")</p>
</div>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model EauSalon.Models.Client
@using EauSalon.Models

<h3>Client Details</h3>
<hr>
<div class="details">
  <h4>@Html.DisplayNameFor(model => model.Name) @Html.DisplayFor(model => model.Name)</h4>
  <h4>@Html.DisplayNameFor(model => model.PreferredDays) @Html.DisplayFor(model => model.PreferredDays)</h4>
  <h4>@Html.DisplayNameFor(model => model.ShortNotice) @Html.DisplayFor(model => model.ShortNotice)</h4>
  <h4>@Html.DisplayNameFor(model => model.Stylist) @Html.DisplayFor(model => model.Stylist)</h4>
</div>

<div class="linked">
  <p>@Html.ActionLink("See list of EauSalon Stylists", "Index", "Stylists")</p>
  <p>@Html.ActionLink("Add an EauSalon Stylist to your records", "Create", "Stylists")</p>
  <p>@Html.ActionLink("See list of EauSalon Clients", "Index", "Clients")</p>
  <p>@Html.ActionLink("Add a new record for an EauSalon client", "Create", "Clients")</p>
</div>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using EauSalon.Models
@model List<EauSalon.Models.Client>

<h1>EauSalon's Clients</h1>


  @if(@Model.Count == 0)
  { 
    <div class="notice">
      <p>There are currently no records of any Clients at EauSalon.</p>
      <p>If you'd like to add a Client to your records, click on the link below.</p>
    </div>
    <p class="linked">@Html.ActionLink("Add an EauSalon Client to your records", "Create", "Clients")</p>
  }
  else
  {
    <div class="details">
    @foreach (Client client in Model)
    {
      <h3 class="client">@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</h3>
    }
    </div>

    <div class="linked">
      <p>@Html.ActionLink("Add an EauSalon Stylist to your records", "Create", "Stylists")</p>
      <p>@Html.ActionLink("Add a new record for an EauSalon client", "Create", "Clients")</p>
    </div>
  }

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Hello Claire! Welcome to your EauSalon Organizer.</h1>

<p class="linked">@Html.ActionLink("See list of EauSalon Stylists", "Index", "Stylists")</p>

HairSalon/Views/Shared/Footer.cshtml
      <footer id="footer">
        <p>@Html.ActionLink("Home", "Index", "Home")</p>
        <P>Background image by Raphael Lovaski on Unsplash</P>
        @* <p>@Html.ActionLink("Background image by Raphael Lovaski on Unsplash", "https://unsplash.com/@raphaellovaski?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText", "https://unsplash.com/s/photos/salon?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText")</p> *@
        @* LINK TO PHOTOGRAPHER *@
      </footer>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>EauSalon Organizer</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
    </div>
    @Html.Partial("Footer")
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model EauSalon.Models.Stylist
@using EauSalon.Models

<h3>Add an EauSalon Stylist to your records</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })

  <input type="submit" value="Add a Stylist" class="btn btn-default">
}


<p class="linked">@Html.ActionLink("See list of EauSalon Stylists", "Index", "Stylists")</p>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model EauSalon.Models.Stylist
@using EauSalon.Models

<h3>Stylist Details</h3>
<hr>
<h3>@Html.DisplayNameFor(model => model.Name) @Html.DisplayFor(model => model.Name)</h3>
<div class="linked">
  <p>@Html.ActionLink("See list of EauSalon Stylists", "Index", "Stylists")</p>
  <p>@Html.ActionLink("Add an EauSalon Stylist to your records", "Create", "Stylists")</p>
  <p>@Html.ActionLink("See list of EauSalon Clients", "Index", "Clients")</p>
  <p>@Html.ActionLink("Add a new record for an EauSalon client", "Create", "Clients")</p>
</div>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using EauSalon.Models
@model List<EauSalon.Models.Stylist>

<h1>EauSalon's Stylists</h1>

@if(@Model.Count == 0)
{ 
  <div class="notice">
    <p>There are currently no records of any Stylists at EauSalon.</p>
    <p>If you'd like to add a Stylist to your records, click on the link below.</p>
  </div>
  <p class="linked">@Html.ActionLink("Add an EauSalon Stylist to your records", "Create", "Stylists")</p>
}
else
{
  <ul>
    @foreach (Stylist stylist in Model)
    {
      <li>@Html.ActionLink($"{stylist.Name}", "Details", new {id = stylist.StylistId})</li>
    }
  </ul>
  <div class="linked">
    <p>@Html.ActionLink("Add an EauSalon Stylist to your records", "Create", "Stylists")</p>
    <p>@Html.ActionLink("Add a new record for an EauSalon client", "Create", "Clients")</p>
  </div>
}